FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Set the timezone to Asia/Tokyo
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# Install dependencies
RUN apt update && apt install -y cmake \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3.10-venv \
    python3-pip \
    portaudio19-dev \
    libsndfile1-dev \
    libhdf5-dev \
    libgl1-mesa-dev \
    libopencv-dev \
    zip \
    unzip

# For development
RUN apt update && apt install -y tmux \
    emacs \
    vim \
    neovim \
    less \
    git \
    pkg-config \
    wget \
    curl \
    git-lfs
RUN apt clean

WORKDIR /home/ubuntu/dslc7

# Install python dependencies
COPY pyproject.toml README.md /home/ubuntu/dslc7/
RUN pip install -e .

COPY . .
