FROM python:3.12-slim

RUN pip install --upgrade pip && pip install poetry==1.8.4

WORKDIR /app
COPY pyproject.toml poetry.lock /app/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

COPY ./logger /app/logger

CMD poetry run python logger/main.py
